#!/bin/sh
echo "Content-type: text/html" # Tells the browser what kind of content to expect
echo "" # An empty line. Mandatory, if it is missed the page content will not load
killall stream_udp_data
./fiforeader 480000
./stream_udp_data 192.168.2.100 > /dev/null 2>&1 &
